
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://zumvhtmqbwxkcbhlqjyl.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bXZodG1xYnd4a2NiaGxxanlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODEzODMsImV4cCI6MjA1ODI1NzM4M30.LUY254461rWC9IE7KU86ezvYKe4A0GZT_zkEFsezits";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Clear any stale auth data before initializing, only for initial application load
if (typeof window !== 'undefined') {
  if (!window.SUPABASE_INITIALIZED) {
    window.SUPABASE_INITIALIZED = true;
    try {
      // First check if we have a valid access token
      const storedAuth = localStorage.getItem('supabase-auth');
      if (!storedAuth) {
        console.log('No stored auth data found, cleaning up any stale data');
        // Remove any potential stale auth data
        Object.keys(localStorage).forEach(key => {
          if (key.startsWith('supabase.auth.') || key === 'supabase-auth') {
            localStorage.removeItem(key);
          }
        });
        console.log('Cleaned up stale auth data on initialization');
      } else {
        try {
          // Validate stored auth data format
          const parsedAuth = JSON.parse(storedAuth);
          if (!parsedAuth.access_token || !parsedAuth.refresh_token) {
            console.warn('Invalid auth data format found, cleaning up');
            localStorage.removeItem('supabase-auth');
          } else {
            console.log('Found valid stored auth data on initialization');
          }
        } catch (e) {
          console.warn('Corrupted auth data found, cleaning up');
          localStorage.removeItem('supabase-auth');
        }
      }
      
      // Also clean up any orphaned active session markers
      console.log('Checking for orphaned auth data on startup');
      const orphanedSessions = [];
      Object.keys(localStorage).forEach(key => {
        if (key.startsWith('active_session_')) {
          orphanedSessions.push(key);
        }
      });
      
      if (orphanedSessions.length > 0) {
        console.log('Cleaning up orphaned auth data:', orphanedSessions);
        orphanedSessions.forEach(key => {
          localStorage.removeItem(key);
        });
      }
    } catch (e) {
      console.warn('Failed to clean localStorage:', e);
    }
  }
}

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
      storageKey: 'supabase-auth',
      flowType: 'implicit'
    },
    global: {
      headers: {
        'Content-Type': 'application/json'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Helper function to check if Supabase is properly configured
export const isSupabaseConfigured = () => {
  return Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
};

// Improved session refresh function with better cross-tab support
export const refreshSessionIfNeeded = async () => {
  try {
    const { data } = await supabase.auth.getSession();
    if (data.session) {
      // Check if token is close to expiry (less than 10 minutes)
      const expiresAt = data.session.expires_at;
      if (expiresAt) {
        const expiryTime = new Date(expiresAt * 1000);
        const now = new Date();
        const tenMinutesInMs = 10 * 60 * 1000;
        
        if (expiryTime.getTime() - now.getTime() < tenMinutesInMs) {
          console.log('Token close to expiry, refreshing session');
          const { data: refreshData, error } = await supabase.auth.refreshSession();
          
          if (error) {
            console.error('Error refreshing session:', error);
            
            // Try to fix possible corrupted session state
            if (error.message.includes('invalid token') || error.message.includes('JWT')) {
              try {
                console.log('Attempting to recover from invalid token error');
                await supabase.auth.signOut({ scope: 'local' });
                localStorage.removeItem('supabase-auth');
                
                // Clear other potential auth-related keys
                Object.keys(localStorage).forEach(key => {
                  if (key.startsWith('supabase.auth.')) {
                    localStorage.removeItem(key);
                  }
                });
                
                console.log('Session state cleared due to invalid token');
                return null;
              } catch (cleanupError) {
                console.error('Error cleaning up corrupted session:', cleanupError);
              }
            }
            
            return null;
          }
          
          // Broadcast session refresh to other tabs
          if (refreshData.session) {
            try {
              const timestamp = Date.now();
              localStorage.setItem('session_refresh_timestamp', timestamp.toString());
              localStorage.setItem('session_expires_at', (refreshData.session.expires_at || 0).toString());
              
              // Also create a unique session ID to track multiple sessions
              if (!localStorage.getItem(`active_session_${refreshData.session.access_token.slice(-8)}`)) {
                localStorage.setItem(`active_session_${refreshData.session.access_token.slice(-8)}`, timestamp.toString());
              }
            } catch (e) {
              console.warn('Failed to broadcast session refresh:', e);
            }
          }
          
          return refreshData.session;
        }
      }
      return data.session;
    }
  } catch (error) {
    console.error('Error refreshing session:', error);
  }
  return null;
};

// Listen for session changes from other tabs
if (typeof window !== 'undefined') {
  window.addEventListener('storage', (event) => {
    if (event.key === 'session_refresh_timestamp' || 
        event.key === 'supabase-auth' || 
        event.key === 'access_token_updated') {
      // Another tab refreshed the session, sync our state
      console.log('Session updated in another tab, syncing local state');
      supabase.auth.getSession().catch(error => {
        console.error('Error syncing session from another tab:', error);
      });
    }
  });
}
